[project]
name = 'my-stacks-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = 4
epoch = 'latest'

[contracts.daily-checkin]
path = 'contracts/daily-checkin.clar'
clarity_version = 4
epoch = 'latest'

[contracts.message-board]
path = 'contracts/message-board.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
